version: '3.7'

services:
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=techtest_db
      - POSTGRES_PASSWORD=techtest_db
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
